# Đường dẫn 
root_path: "D:/PMT_Paper/src/dataset/roboflow_dl"
train_ann: "${root_path}/train/_annotations.coco.json"
val_ann:   "${root_path}/valid/_annotations.coco.json"

# DataLoader
batch_train: 16
batch_val: 8
num_workers: 0
pin_memory: true

# Train
epochs: 200
lr: 1.0e-4
step_size: 30
gamma: 0.1
seed: 42

# Eval
conf_eval: 0.30

# Save
save_dir: "output"
save_pred_map: true
save_pred_map_split: "valid"   # valid|test
